#!/bin/bash
export GIT_COMMITTER_DATE="Wed Dec 16 19:01 2018 +0100"
   export GIT_AUTHOR_DATE="Wed Dec 16 19:01 2018 +0100"
git add .
git commit -am " new update to code scripts"
git push origin master
